<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="3.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:output method="text" indent="no" encoding="utf-8"/>

  <xsl:template match="/">
## Do not edit this file. It is generated automatically 
##   by body/AAUHuman/BuildTools/anyxdefs.bat

# Mapping BM Contatnts to values
{
<xsl:apply-templates select="anyxdefs/constant" />}
</xsl:template>


<xsl:template match="constant">'<xsl:value-of select="@name"/>': '<xsl:value-of select="@default"/>',
</xsl:template>

</xsl:stylesheet>