# This aciton will only work on Windows runners

name: 'Use Custom AnyBodyCon from Azure Blob storage'

description: 'Download specific anybodycon version from Azure Blob storage'

inputs:
  custom-anybodycon:  # path
    description: 'The AnyBodyCon version to use'
    required: true
  connection-string:
    description: 'The connection string to the Azure Blob storage'
    required: true
    
runs:
  using: "composite"
  steps: 
    - name: Create temp location for AnyBodyCon
      if: ${{ inputs.custom-anybodycon }}
      shell: powershell
      run: mkdir -p ${{ runner.temp }}/$(split-path ${{ inputs.custom-anybodycon }} -Parent)
      
    - name: Get special AnyBodyCon version
      if: ${{ inputs.custom-anybodycon }}
      uses: armanrahman22/azblob-download-action@main
      with:
        connection-string: ${{ inputs.connection-string }}
        container-name: "anybodycon"
        blob-name: ${{ inputs.custom-anybodycon }}
        download-path: ${{ runner.temp }}
      
    - name: Overwrite AnyBodyCon
      if: ${{ inputs.custom-anybodycon }}
      shell: powershell
      run: |
        cp ${{ runner.temp }}\${{ inputs.custom-anybodycon }} "$(split-path $Env:ANYBODYCON -Parent)/AnyBodyConCustom.any"
        echo "ANYBODYCON=$(split-path $Env:ANYBODYCON -Parent)\AnyBodyConCustom.any" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append








    - run: ${{ github.action_path }}/ExecuteSomething.sh
      shell: bash
    - id: random-number-generator
      run: echo "::set-output name=filesNo::$(echo $RANDOM)"
      shell: bash
    - run: ${{ github.action_path }}/CopyFiles.sh
      shell: bash


  