# This aciton will only work on Windows runners

name: 'Use Custom AnyBodyCon from Azure Blob storage'

description: 'Download specific anybodycon version from Azure Blob storage'

inputs:
  custom-anybodycon:  # path
    description: 'The AnyBodyCon version to use'
    required: true
  connection-string:
    description: 'The connection string to the Azure Blob storage'
    required: true
  overwrite:
    description: 'Overwrite the AnyBodyCon version in the GitHub runner'
    required: false
    default: false
    
runs:
  using: "composite"
  steps: 
    - name: Create temp location for AnyBodyCon
      if: ${{ inputs.custom-anybodycon }}
      shell: powershell
      run: mkdir -p ${{ runner.temp }}/$(split-path ${{ inputs.custom-anybodycon }} -Parent)
      
    - name: Get special AnyBodyCon version
      if: ${{ inputs.custom-anybodycon }}
      uses: armanrahman22/azblob-download-action@main
      with:
        connection-string: ${{ inputs.connection-string }}
        container-name: "anybodycon"
        blob-name: ${{ inputs.custom-anybodycon }}
        download-path: ${{ runner.temp }}
      
    - name: Update AnyBodyCon environment variable
      if: ${{ ! inputs.overwrite }}
      shell: powershell
      run: |
        cp ${{ runner.temp }}\${{ inputs.custom-anybodycon }} "$(split-path $Env:ANYBODYCON -Parent)/AnyBodyConCustom.any"
        echo "ANYBODYCON=$(split-path $Env:ANYBODYCON -Parent)\AnyBodyConCustom.any" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

    - name: Overwrite existing AnyBodyCon version
      if: ${{ inputs.overwrite }}
      shell: powershell
      run: |
        $anybodycon = (Get-ItemProperty -Path "Registry::HKEY_CLASSES_ROOT\AnyBody.AnyScript\shell\open\command" -Name "(default)")."(default)"
        $anybodycon = $anybodycon.split('"')[2]
        cp ${{ runner.temp }}\${{ inputs.custom-anybodycon }} "$anybodycon"



  