[project]
name = "ammr-docs"
authors = ["Morten Enemark Lund <mel@anybodytech.com>"]
channels = ["conda-forge"]
repository = "https://github.com/anybody/ammr"
documentation = "https://anyscript.org/ammr"
platforms = ["linux-64", "win-64"]

[tasks]
html = "sphinx-build -M html . _build -W --keep-going"
linkcheck = "sphinx-build -M linkcheck . _build -W --keep-going -a -q "
clean = "rm -rf _build"


[dependencies]
python = "3.11.*"
sphinx-book-theme = ">=1.1.0,<1.2"
sphinx-thebe = ">=0.2.1,<0.3"
sphinxcontrib-youtube = ">=1.4.1,<1.5"
sphinx-tabs = ">=3.4.1,<3.5"
sphinx-design = ">=0.5.0,<0.6"
sphinx-togglebutton = ">=0.3.2,<0.4"
sphinxext-opengraph = ">=0.9.1,<0.10"
sphinxcontrib-bibtex = ">=2.5.0,<2.6"
sphinx-copybutton = ">=0.5.2,<0.6"
myst-parser = ">=2.0.0,<2.1"
pygments_anyscript = ">=1.3.0,<1.4"
jinja2 = ">=3.1.3,<3.2"
python-frontmatter = ">=1.1.0,<1.2"
pydantic = ">=2.5.3,<2.6"
tqdm = ">=4.66.1,<4.67"

