[project]
name = "ammr-docs"
authors = ["Morten Enemark Lund <mel@anybodytech.com>"]
channels = ["conda-forge"]
repository = "https://github.com/anybody/ammr"
documentation = "https://anyscript.org/ammr"
platforms = ["linux-64", "win-64"]

[tasks]
html = "sphinx-build -M html . _build -W --keep-going"
linkcheck = "sphinx-build -M linkcheck . _build -W --keep-going -a -q "
clean = "rm -rf _build"


[dependencies]
python = "3.11.*"
sphinx = "6.*"
myst-parser = "*"
pygments_anyscript = "*"
matplotlib = "*"
pillow = "*"
jinja2 = "*"
sphinx-design = "*"
tomli = "*"
pyYAML = "*"
sphinx-togglebutton = "*"
sphinx-copybutton = "*"
python-frontmatter = "*"
sphinxext-opengraph = "*"
pydantic = "*"
tqdm = "*"
make = "*"
pydata-sphinx-theme = "0.13.*"
sphinx-book-theme = "1.0.1.*"
