[project]
name = "ammr-docs"
authors = ["Morten Enemark Lund <mel@anybodytech.com>"]
channels = ["conda-forge"]
repository = "https://github.com/anybody/ammr"
documentation = "https://anyscript.org/ammr"
platforms = ["linux-64", "win-64"]

[tasks]
html = {cmd = [
    "sphinx-build", "-M", "html", ".", "_build","-W", "--keep-going"
] }
clean = "rm -rf _build"


[dependencies]
python = "3.11.*"
sphinx = "*"
myst-parser = "*"
pygments_anyscript = "*"
matplotlib = "*"
pillow = "*"
jinja2 = "*"
sphinx-design = "*"
tomli = "*"
pyYAML = "*"
sphinx-togglebutton = "*"
sphinx-copybutton = "*"
python-frontmatter = "*"
sphinxext-opengraph = "*"
sphinx-book-theme= "*"
pydantic = "*"
tqdm = "*"
