# This aciton will only work on Windows runners

name: 'Install Micro mamba'

description: 'Download and install micromamba on the selfhosted runner'

inputs:
  environment-file:  # path
    description: 'A conda environment file to install'
    required: false
  environment-name:
    description: 'The name of the conda environment to create'
    required: false
    default: 'base'
    
runs:
  using: "composite"
  steps: 
      - name: Install conda
        shell: powershell
        run: | 
          Invoke-Webrequest -URI https://anaconda.org/conda-forge/micromamba/1.4.3/download/win-64/micromamba-1.4.3-0.tar.bz2 -OutFile ~\micromamba.tar.bz2
          (Get-FileHash ~\micromamba.tar.bz2).hash -eq "ED3B12B747F05A630198D3A8A8F7120BDE22AE9033CB62AF95D6F3DF57FE9B0C"
          $env:Path = "C:\PROGRA~1\Git\usr\bin;" + $env:Path
          tar -xvjf ~/micromamba.tar.bz2 --strip-components 2 -C ~ Library/bin/micromamba.exe
          echo "MAMBA_ROOT_PREFIX=$HOME\micromamba" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create conda environment
        if: ${{ inputs.environment-file }}
        shell: powershell
        run: |
          ~\micromamba.exe shell hook -s powershell | Out-String | iex
          micromamba create --allow-downgrade -y -n ${{ inputs.environment-file }} -f ${{ inputs.environment-file }}
