# This aciton will only work on Windows runners

name: 'Install Micro mamba'

description: 'Download and install micromamba on the selfhosted runner'

inputs:
  environment-file:  # path
    description: 'A conda environment file to install'
    required: false
    default: ''
  environment-name:
    description: 'The name of the conda environment to create'
    required: false
    default: ''
    
runs:
  using: "composite"
  steps: 
      - name: Install conda
        shell: powershell
        run: | 
          Invoke-Webrequest -URI https://anaconda.org/conda-forge/micromamba/1.5.3/download/win-64/micromamba-1.5.3-0.tar.bz2 -OutFile ~\micromamba.tar.bz2
          if ((Get-FileHash ~\micromamba.tar.bz2).hash -ne "9BAA0A4C432DF2509C2911C8A4D373FACFADAB629792EE8CE56F28D5B007390D") {exit 1}
          $env:Path = "C:\PROGRA~1\Git\usr\bin;" + $env:Path
          tar -xvjf ~/micromamba.tar.bz2 --strip-components 2 -C ~ Library/bin/micromamba.exe
          echo "MAMBA_ROOT_PREFIX=$HOME\micromamba" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create conda environment (custom name)
        if: inputs.environment-file != '' &&  inputs.environment-name != ''
        shell: powershell
        run: |
          ~\micromamba.exe shell hook -s powershell | Out-String | iex
          micromamba create --allow-downgrade -y -n ${{ inputs.environment-name }} -f ${{ inputs.environment-file }}

      - name: Create conda environment 
        if: inputs.environment-file != '' &&  inputs.environment-name == ''
        shell: powershell
        run: |
          ~\micromamba.exe shell hook -s powershell | Out-String | iex
          micromamba create --allow-downgrade -y -f ${{ inputs.environment-file }}
