name: Tests (Forks)


on:
  pull_request_target:
    types: [labeled]

concurrency: 
  group: test-forks-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'safe to test') && github.event.pull_request.head.repo.fork }}
    
    strategy:
      fail-fast: false
      matrix:
        test_group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    runs-on: windows-latest
    
    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: anybody/setup-anybody@main
        name: Install AnyBody
        with:
          anybody-version: "7.5.0"
          anybody-version-suffix: "Beta"

      - uses: prefix-dev/setup-pixi@v0.4.1
        with:
          cache: false
  
      - name: Run AMMR tests
        run: |
          cd Tests
          pixi run pytest -n auto --dist worksteal `
             --splits 10 --group ${{ matrix.test_group }} --splitting-algorithm=least_duration `
             --durations=10 `
             --runslow
        env:
          RLM_LICENSE: ${{ secrets.LICENSE_SERVER }}
          RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_PASSWORD }}
