name: AMMR container tests

on:
  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    container: ghcr.io/anybody/anybodycon-linux:latest

    steps:
    
      - uses: actions/checkout@v2

      - name: AMMR tests
        env:
          RLM_LICENSE: 5053@104.46.46.229
          RLM_LICENSE_PASSWORD: ${{ secrets.LICENSE_PASSWORD }}
        run: pytest Tests 



