name: debug tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:


concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    
    strategy:
      fail-fast: false

    env:
      ShortestPathMaxAngle: 0.3491 

    runs-on: [self-hosted, AnyBody]
    
    steps:
      - uses: actions/checkout@v2

      - name: debug
        env: 
          USERNAME: "N"
        run: |
          gci env:
