name: AMMR tests

on:
  push:
    branches: [ master ]
  workflow_dispatch:

concurrency: 
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    
    strategy:
      fail-fast: false

    env:
      ShortestPathMaxAngle: 0.3491 

    runs-on: [self-hosted, AnyBody]
    
    steps:
      - uses: actions/checkout@v2

      - name: debug
        run: |
          echo $env:USERNAME
          echo $env:USERDOMAIN
